# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.cache/wt [current_project]
set_property parent.project_path E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
set_property ip_repo_paths {
  E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/ip_repo/myip_1.0
  E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.srcs/sources_1
} [current_project]
add_files -quiet E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.runs/haystack_mem_synth_1/haystack_mem.dcp
set_property used_in_implementation false [get_files E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.runs/haystack_mem_synth_1/haystack_mem.dcp]
add_files -quiet E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.runs/needle_mem_synth_1/needle_mem.dcp
set_property used_in_implementation false [get_files E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.runs/needle_mem_synth_1/needle_mem.dcp]
add_files -quiet E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.runs/axi_haystack_mem_ctrl_synth_1/axi_haystack_mem_ctrl.dcp
set_property used_in_implementation false [get_files E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.runs/axi_haystack_mem_ctrl_synth_1/axi_haystack_mem_ctrl.dcp]
add_files -quiet E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.runs/axi_needle_mem_ctrl_synth_1/axi_needle_mem_ctrl.dcp
set_property used_in_implementation false [get_files E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.runs/axi_needle_mem_ctrl_synth_1/axi_needle_mem_ctrl.dcp]
read_verilog -library xil_defaultlib {
  E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.srcs/sources_1/control_registers.v
  E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.srcs/sources_1/bitap.v
  E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.srcs/sources_1/search_block.v
}
catch { write_hwdef -file search_block.hwdef }
synth_design -top search_block -part xc7z020clg484-1
write_checkpoint -noxdef search_block.dcp
catch { report_utilization -file search_block_utilization_synth.rpt -pb search_block_utilization_synth.pb }
