# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.cache/wt [current_project]
set_property parent.project_path C:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
set_property ip_repo_paths c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/SearchBlock [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/base_zynq_design.bd
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_blk_mem_gen_0_0/base_zynq_design_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_bram_ctrl_0_0/base_zynq_design_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_100M_0/base_zynq_design_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_100M_0/base_zynq_design_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_100M_0/base_zynq_design_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/ip/axi_needle_mem_ctrl/axi_needle_mem_ctrl_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/ip/axi_haystack_mem_ctrl/axi_haystack_mem_ctrl_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/ip/needle_mem/needle_mem_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/ip/haystack_mem/haystack_mem_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_xbar_0/base_zynq_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_pc_0/base_zynq_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_pc_1/base_zynq_design_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_pc_2/base_zynq_design_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/base_zynq_design_ooc.xdc]
set_property is_locked true [get_files C:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/base_zynq_design.bd]

read_verilog -library xil_defaultlib C:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/sources_1/bd/base_zynq_design/hdl/base_zynq_design_wrapper.v
read_xdc C:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/constrs_1/new/base_zynq_design_wrapper.xdc
set_property used_in_implementation false [get_files C:/Users/Anonymouse/Dropbox/Projects/Complex/mrtech/fsearch/FPGA/System/System.srcs/constrs_1/new/base_zynq_design_wrapper.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top base_zynq_design_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef base_zynq_design_wrapper.dcp
catch { report_utilization -file base_zynq_design_wrapper_utilization_synth.rpt -pb base_zynq_design_wrapper_utilization_synth.pb }
