# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/base_zynq_design_wrapper.xdc

# Block Designs: bd/base_zynq_design/base_zynq_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design || ORIG_REF_NAME==base_zynq_design}]

# IP: bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_processing_system7_0_0 || ORIG_REF_NAME==base_zynq_design_processing_system7_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_gpio_0_0 || ORIG_REF_NAME==base_zynq_design_axi_gpio_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_blk_mem_gen_0_0/base_zynq_design_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_blk_mem_gen_0_0 || ORIG_REF_NAME==base_zynq_design_blk_mem_gen_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_bram_ctrl_0_0/base_zynq_design_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==base_zynq_design_axi_bram_ctrl_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_axi_periph_0/base_zynq_design_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==base_zynq_design_processing_system7_0_axi_periph_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_100M_0/base_zynq_design_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==base_zynq_design_rst_processing_system7_0_100M_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/base_zynq_design_search_block_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_search_block_0_1 || ORIG_REF_NAME==base_zynq_design_search_block_0_1}]

# IP: bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/ip/axi_needle_mem_ctrl/axi_needle_mem_ctrl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_needle_mem_ctrl || ORIG_REF_NAME==axi_needle_mem_ctrl}]

# IP: bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/ip/axi_haystack_mem_ctrl/axi_haystack_mem_ctrl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_haystack_mem_ctrl || ORIG_REF_NAME==axi_haystack_mem_ctrl}]

# IP: bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/ip/needle_mem/needle_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==needle_mem || ORIG_REF_NAME==needle_mem}]

# IP: bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/ip/haystack_mem/haystack_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==haystack_mem || ORIG_REF_NAME==haystack_mem}]

# IP: bd/base_zynq_design/ip/base_zynq_design_xbar_0/base_zynq_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_xbar_0 || ORIG_REF_NAME==base_zynq_design_xbar_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_auto_pc_0/base_zynq_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_auto_pc_0 || ORIG_REF_NAME==base_zynq_design_auto_pc_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_auto_pc_1/base_zynq_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_auto_pc_1 || ORIG_REF_NAME==base_zynq_design_auto_pc_1}]

# IP: bd/base_zynq_design/ip/base_zynq_design_auto_pc_2/base_zynq_design_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_auto_pc_2 || ORIG_REF_NAME==base_zynq_design_auto_pc_2}]

# XDC: bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_processing_system7_0_0 || ORIG_REF_NAME==base_zynq_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_gpio_0_0 || ORIG_REF_NAME==base_zynq_design_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_gpio_0_0 || ORIG_REF_NAME==base_zynq_design_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_blk_mem_gen_0_0/base_zynq_design_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_bram_ctrl_0_0/base_zynq_design_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_100M_0/base_zynq_design_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==base_zynq_design_rst_processing_system7_0_100M_0}]

# XDC: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_100M_0/base_zynq_design_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==base_zynq_design_rst_processing_system7_0_100M_0}]

# XDC: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_100M_0/base_zynq_design_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/ip/axi_needle_mem_ctrl/axi_needle_mem_ctrl_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/ip/axi_haystack_mem_ctrl/axi_haystack_mem_ctrl_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/ip/needle_mem/needle_mem_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_search_block_0_1/ip/haystack_mem/haystack_mem_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_xbar_0/base_zynq_design_xbar_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_auto_pc_0/base_zynq_design_auto_pc_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_auto_pc_1/base_zynq_design_auto_pc_1_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_auto_pc_2/base_zynq_design_auto_pc_2_ooc.xdc

# XDC: bd/base_zynq_design/base_zynq_design_ooc.xdc
