# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.srcs/sources_1/ip/axi_needle_mem_ctrl/axi_needle_mem_ctrl.xci
# IP: The module: 'axi_needle_mem_ctrl' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.srcs/sources_1/ip/axi_needle_mem_ctrl/axi_needle_mem_ctrl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_needle_mem_ctrl'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.srcs/sources_1/ip/axi_needle_mem_ctrl/axi_needle_mem_ctrl.xci
# IP: The module: 'axi_needle_mem_ctrl' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Dropbox/Dropbox/Projects/Complex/ZedBoard/fsearch/FPGA/SearchBlock/SearchBlock.srcs/sources_1/ip/axi_needle_mem_ctrl/axi_needle_mem_ctrl_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_needle_mem_ctrl'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
